// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class CategoriesTbl
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<ProductTbl> ProductTbls { get; set; } = new List<ProductTbl>();
}