// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class OrdersTbl
{
    public int OrderId { get; set; }

    public DateOnly OrderDate { get; set; }

    public double? OrderSum { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<OrderItemsTbl> OrderItemsTbls { get; set; } = new List<OrderItemsTbl>();

    public virtual User User { get; set; }
}