// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class ProductTbl
{
    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescribtion { get; set; }

    public double? ProductPrice { get; set; }

    public string ProductPicture { get; set; }

    public virtual CategoriesTbl Category { get; set; }
}