// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Entities;
using Microsoft.EntityFrameworkCore;

namespace Repository;

public partial class ShopContext : DbContext
{
    public ShopContext(DbContextOptions<ShopContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CategoriesTbl> CategoriesTbls { get; set; }

    public virtual DbSet<ProductTbl> ProductTbls { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CategoriesTbl>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.ToTable("Categories_tbl");

            entity.Property(e => e.CategoryId).HasColumnName("Category_id");
            entity.Property(e => e.CategoryName).HasColumnName("Category_name");
        });

        modelBuilder.Entity<ProductTbl>(entity =>
        {
            entity.HasKey(e => e.ProductId);

            entity.ToTable("Product_tbl");

            entity.Property(e => e.ProductId).HasColumnName("Product_id");
            entity.Property(e => e.CategoryId).HasColumnName("Category_id");
            entity.Property(e => e.ProductDescribtion).HasColumnName("Product_describtion");
            entity.Property(e => e.ProductName).HasColumnName("Product_name");
            entity.Property(e => e.ProductPicture)
                .IsUnicode(false)
                .HasColumnName("Product_picture");
            entity.Property(e => e.ProductPrice).HasColumnName("Product_price");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductTbls)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Product_tbl_Categories_tbl");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId).HasColumnName("User_id");
            entity.Property(e => e.FirstName).HasColumnName("First_name");
            entity.Property(e => e.LastName).HasColumnName("Last_name");
            entity.Property(e => e.Password)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasColumnName("User_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    internal async Task<User> FindAsync(UserLog userToLog)
    {
        throw new NotImplementedException();
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}